name: Generate VHS GIFs 📼

on:
  push:
    paths:
      - '.vhs/*.tape'
  workflow_dispatch:

jobs:
  vhs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup VHS
        uses: charmbracelet/vhs-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: '.vhs/about_me.tape'

      - name: Setup VHS - Mission Log
        uses: charmbracelet/vhs-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: '.vhs/mission_log.tape'

      - name: Commit Action generated GIFs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update VHS GIFs"
          branch: output
          create_branch: true
          push_options: '--force'
          file_pattern: 'dist/*.gif'
