name: Generate VHS GIFs 📼

on:
  push:
    paths:
      - '.vhs/*.tape'
  workflow_dispatch:

jobs:
  vhs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install FFmpeg and ttyd
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg pv jq

          sudo curl -L https://github.com/tsl0922/ttyd/releases/download/1.7.2/ttyd.x86_64 -o /usr/local/bin/ttyd
          sudo chmod +x /usr/local/bin/ttyd
        
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install VHS
        run: |
          go install github.com/charmbracelet/vhs@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Generate About Me GIF
        run: vhs .vhs/about_me.tape

      - name: Generate Mission Log GIF
        run: vhs .vhs/mission_log.tape

      - name: Commit GIFs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update VHS GIFs"
          branch: output
          create_branch: true
          push_options: '--force'
          file_pattern: 'dist/*.gif'